### ISSUE TITLE
NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by gtoto007** [keijiro/Khoreo#1]
Unity  2019.3.9f1 Personal - Macbook pro 2016 late - Catalina

I've infinity exceptions in editor and play mode 

`NullReferenceException: Object reference not set to an instance of an object
Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle.CheckReadAndThrow (Unity.Collections.LowLevel.Unsafe.AtomicSafetyHandle handle) (at /Users/builduser/buildslave/unity/build/Runtime/Export/Jobs/AtomicSafetyHandle.bindings.cs:142)
Unity.Collections.LowLevel.Unsafe.NativeSliceUnsafeUtility.GetUnsafeReadOnlyPtr[T] (Unity.Collections.NativeSlice`1[T] nativeSlice) (at /Users/builduser/buildslave/unity/build/Runtime/Export/NativeArray/NativeSlice.cs:446)
Unity.Collections.NativeSlice`1[T].CopyTo (Unity.Collections.NativeArray`1[T] array) (at /Users/builduser/buildslave/unity/build/Runtime/Export/NativeArray/NativeSlice.cs:265)
Lasp.Vfx.VFXWaveformBinder.UpdateTexture () (at Library/PackageCache/jp.keijiro.laspvfx@1.0.0/Runtime/VFXWaveformBinder.cs:101)
Lasp.Vfx.VFXWaveformBinder.UpdateBinding (UnityEngine.VFX.VisualEffect component) (at Library/PackageCache/jp.keijiro.laspvfx@1.0.0/Runtime/VFXWaveformBinder.cs:48)
UnityEngine.VFX.Utility.VFXPropertyBinder.Update () (at Library/PackageCache/com.unity.visualeffectgraph@7.3.1/Runtime/Utilities/PropertyBinding/VFXPropertyBinder.cs:55)
`
<img width="1676" alt="Schermata 2020-05-15 alle 11 15 42" src="https://user-images.githubusercontent.com/6715157/82033742-77abc880-969d-11ea-901b-3ad45a75bfa6.png">

**Comment by keijiro** [comment]
This project uses Roland MC-101 synthesizer as audio input. You have to reassign it when you try to run the project with other devices.
